# Generated by Django 3.2.9 on 2021-11-14 08:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_name', models.CharField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 45 characters or fewer. Letters, digits and _.', max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9-._]+$', 'Enter a valid username. This value may contain only letters, numbers and ._ characters.', 'invalid')], verbose_name='username')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that email already exists.'}, help_text='Required. a valid email address for verification ', max_length=254, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9._@]+$', 'Enter a valid email address. This value may contain only letters, numbers and _@. ', 'invalid')], verbose_name='email address')),
                ('first_name', models.CharField(blank=True, error_messages={'': 'Required. a valid characters.'}, help_text='Required. a valid first name', max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Required. a valid name characters. ', 'invalid')], verbose_name='first name')),
                ('last_name', models.CharField(blank=True, error_messages={'': 'Required. a valid characters.'}, help_text='Required. a valid last name', max_length=45, validators=[django.core.validators.RegexValidator('^[A-Za-z]+$', 'Required. a valid name characters. ', 'invalid')], verbose_name='last name')),
                ('mobile_number', models.CharField(default='000000000', error_messages={'unique': 'A user with that mobile number already exists.'}, help_text='Required. a valid mobile number for verification ', max_length=45, unique=True, validators=[django.core.validators.RegexValidator('^[0-9-._ ]+$', 'Enter a valid mobile number. This value may contain only numbers ', 'invalid')], verbose_name='mobile number')),
                ('is_verified', models.BooleanField(default=False, help_text='Designates whether this user should be allow to have access.', verbose_name='verified status')),
                ('is_moderator', models.BooleanField(default=False, help_text='Designates whether this user should be treated as moderator.', verbose_name='moderator status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin panel. ', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=False, help_text='Designates whether this user should be treated as active. Deactivate this instead of deleting accounts.', verbose_name='active statue')),
                ('is_superuser', models.BooleanField(default=True, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('date_modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date_modified')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='time stamp')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User Register',
                'verbose_name_plural': 'User Registers',
            },
        ),
    ]
